const DB = {
  the: {
    chunks: ['DH', 'AH'],
    phones: ['DH', 'AH'],
  },
  of: { chunks: ['o', 'f'], phones: ['AH', 'V'] },
  and: { chunks: ['a', 'n', 'd'], phones: ['AH', 'N', 'D'] },
  to: { chunks: ['t', 'o'], phones: ['T', 'UW'] },
  a: { chunks: ['a'], phones: ['AH'] },
  in: { chunks: ['i', 'n'], phones: ['IH', 'N'] },
  for: { chunks: ['f', 'o', 'r'], phones: ['F', 'AO', 'R'] },
  is: { chunks: ['i', 's'], phones: ['IH', 'Z'] },
  on: { chunks: ['o', 'n'], phones: ['AA', 'N'] },
  that: { chunks: ['th', 'a', 't'], phones: ['DH', 'AE', 'T'] },
  by: { chunks: ['b', 'y'], phones: ['B', 'AY'] },
  this: { chunks: ['th', 'i', 's'], phones: ['DH', 'IH', 'S'] },
  with: { chunks: ['w', 'i', 'th'], phones: ['W', 'IH', 'DH'] },
  i: { chunks: ['i'], phones: ['AY'] },
  you: { chunks: ['y', 'ou'], phones: ['Y', 'UW'] },
  it: { chunks: ['i', 't'], phones: ['IH', 'T'] },
  not: { chunks: ['n', 'o', 't'], phones: ['N', 'AA', 'T'] },
  or: { chunks: ['o', 'r'], phones: ['AO', 'R'] },
  be: { chunks: ['b', 'e'], phones: ['B', 'IY'] },
  are: { chunks: ['a', 're'], phones: ['AA', 'R'] },
};
export default DB;
